### ISSUE TITLE
[Error] Could not build wheels for aiohttp

### ISSUE THREAD

**Issue by maik123100** [sarartur/chess.com#20]
when trying to use chessdotcom api on fedora OS I've come to the error that with ever way of doing "pip3 install chess.com" the error is "ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects".

Then I've tried the following which didn't help:

1. pip3 install wheel (just to be very safe)
2. pip3 install --upgrade pip setuptools wheel
3. pip3 install aiohttp (This actually worked without error)

Thanky you for help in advance

**Comment by ih8js-git** [comment]
I had the same problem, use the requirements txt, it fixed it for me.
