### ISSUE TITLE
Ability to set user-agent contact information?

### ISSUE THREAD

**Issue by alextoul** [sarartur/chess.com#3]
Hi, Chess.com suggests adding the developer's contact information in order to prevent disruption. 

Could this (amazing) wrapper allow that? 

_In some cases, if we detect abnormal or suspicious activity, we may block your application entirely. If you supply a recognizable user-agent that contains contact information, then if we must block you application we will attempt to contact you to correct the problem._ [link](https://www.chess.com/news/view/published-data-api)

**Comment by sarartur** [comment]
The ability to edit request headers has been added for versions 1.4.1. and higher. The change is already showing in Github.  PyPi is currently down so I can not upload the release there, but as soon as they are fully back up I will update the version there as well.

**Comment by alextoul** [comment]
That was quick. Amazing. Thank you.
