### ISSUE TITLE
Http request returns Base exception in Windows operating system

### ISSUE THREAD

**Issue by sabuhikhalili** [sarartur/chess.com#4]
I was trying to use get_player_profile of chessdotcom package, however, it returned the Chessdotcom error (which doesn't say much). I used the requests package and could get successful response for the url request get_player_profile uses. When I debug, I noticed that response at do_get_request method returns OSerror and zlib error. Changing getter method for windows would help. It would also be good to return original error instead of generic chessdotcom error to make it easier for debugging

```
    @classmethod
    def do_get_request(cls, path):
        r = cls._https.request(
            method='GET',
            url=cls._base_url + path,
            headers=cls.headers
        )
        if r.status != 200:
            raise ChessDotComError(status_code=r.status)
        return r
```

**Comment by sarartur** [comment]
Everything seems to work when I run the tests on my Windows machine. Could you please post the traceback in here?

**Comment by sabuhikhalili** [comment]
`Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Sabuhi Khalili/PycharmProjects/chesscom/main.py", line 10, in <module>
    player = ch.get_player_profile(USERNAME)
  File "C:\Users\Sabuhi Khalili\.conda\envs\temp\lib\site-packages\chessdotcom\client.py", line 39, in get_player_profile
    r = Client.do_get_request(path = f"/player/{username}")
  File "C:\Users\Sabuhi Khalili\.conda\envs\temp\lib\site-packages\chessdotcom\client.py", line 30, in do_get_request
    raise ChessDotComError(status_code=r.status)
chessdotcom.errors.ChessDotComError: [MESSAGE] -- Response not 200.[STATUS CODE] -- 403 [REFERENCE] -- https://www.chess.com/news/view/published-data-api 
python-BaseException

Process finished with exit code 1
`

I also send screenshot of response at debugger

![image](https://user-images.githubusercontent.com/46604895/110173976-b44cda00-7dff-11eb-95df-cce89f294e58.png)

I am using Python 3.7

**Comment by sarartur** [comment]
The server is responding with 403. For some reason you are not allowed to access that resource. Look at this https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403. This might be specific to your IP. 

The chessdotcomerror is returned only if the response code is not 200. The code is working as expected.

I do agree that the errors need to be reworked however since the server also returns more useful information on the error. I will roll out an update tonight.

**Comment by sabuhikhalili** [comment]
Thanks. I also think it might be related to ip as I am using some 'public' network, however this problem only emerges on urllib. Using requests or chrome to get response do not return the same error. I will use requests method in my code as a workaround, just wanted to let you know anyway. Good luck with your work

**Comment by sarartur** [comment]
Yes, I was actually thinking of switching to requests as well. Probably will add that in tonight with proxy support as well.

Thanks for letting me know!

**Comment by sarartur** [comment]
I updated the package to use `requests` package and improved the `ChessDotComError` object.
