### ISSUE TITLE
problem with rate limit

### ISSUE THREAD

**Issue by OracleOfDelphii** [sarartur/chess.com#7]
Hello, this library works like a charm, but I ran into a problem with rate limit of public API.
I want to get the profile of all players that i have played in a certain month, and there are about 1000 games. After certain amount of requests, the server responds with 429 code and Client.loop.run_until_complete throws ChessDotComError(too many requests). What i have tried is to send smaller requests(like 5 users per request) and this works until around 600 users with no problem, but after that a few exceptions are thrown. Is there a way to solve the rate limit problem completely?

**Comment by sarartur** [comment]
I would just lower the number of users per request or put in a sleep statement. Alternatively you can decorate the `Client.do_get_request` method like in the following code:

```python
import time
from chessdotcom import Client
from chessdotcom.types import ChessDotComError

def handle_err(func, retries, time_to_sleep):    
    async def wrapper(*args, **kwargs):
        tries = 0
        while True:
            try:
                response = await func(*args, **kwargs)
            except ChessDotComError as err:
                tries += 1
                if err.status_code == 429 and tries <= retries:
                    time.sleep(time_to_sleep)
                    continue
                raise Exception from err
            else:
                return response
    return wrapper
     
Client.do_get_request = handle_err(Client.do_get_request, 
    retries=3, 
    time_to_sleep=2)
```
And then you can just starting calling the functions

**Comment by OracleOfDelphii** [comment]
I modified the ChessDotComError to contain headers too, so i can get "Retry-after"  header and use time.sleep() as you mentioned. Still 429 error happens but at least the program knows how long it should wait for the next request. The reason i can't lower the numbers of users per request to less than 5, despite it fixes all errors, is that Chess.com API is really slow.
